FROM debian:stretch-slim
RUN true \
  && apt-get update \
  && apt-get -y install \
    binutils \
    bison \
    flex \
    gcc \
    groff-base \
    libbsd-dev \
    libc6-dev \
    make \
    ncurses-dev \
    nvi \
    unzip
