#!/bin/sh

tobuild="$(find . -type f -name Dockerfile -mindepth 2 -maxdepth 2 \
  | sort -n \
  | xargs -n 1 dirname \
  | xargs -n 1 basename)"

echo "# generated by $(basename $0)"
echo "steps:"
for step in $tobuild ; do
  echo "- id: $step"
  echo "  dir: $step"
  echo "  name: 'gcr.io/cloud-builders/docker'"
  echo "  args: [ 'build', '-t', 'gcr.io/\$PROJECT_ID/$step', '.' ]"
done

echo
echo "images:"
for step in $tobuild ; do
  echo "- 'gcr.io/\$PROJECT_ID/$step'"
done
